# Generated by Django 2.2.3 on 2022-10-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Article', 'Article'), ('Question', 'Question'), ('NewsLetter', 'NewsLetter'), ('Other', 'Other')], db_index=True, default='Article', max_length=100),
        ),
    ]
