# Generated by Django 2.2.3 on 2022-10-07 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceye_auth', '0004_account'),
        ('common', '0003_auto_20221007_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='快讯内容')),
                ('good', models.PositiveIntegerField(default=0, verbose_name='利好')),
                ('bad', models.PositiveIntegerField(default=0, verbose_name='利空')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='newsletter_cat', to='common.Category', verbose_name='分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ceye_auth.User', verbose_name='作者')),
            ],
            options={
                'verbose_name': '快讯',
                'verbose_name_plural': '快讯',
            },
        ),
    ]
