# Generated by Django 2.2.3 on 2022-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/%Y/%m/%d/', verbose_name='文章图片'),
        ),
    ]
