# Generated by Django 2.2.3 on 2022-10-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20221007_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_letter',
            field=models.BooleanField(default=True, verbose_name='是不是快讯'),
        ),
    ]
