# Generated by Django 2.2.3 on 2022-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20221007_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
