# Generated by Django 2.2.3 on 2022-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_synced',
            field=models.BooleanField(default=False, verbose_name='是否已经同步'),
        ),
        migrations.AddField(
            model_name='chainsafe',
            name='is_synced',
            field=models.BooleanField(default=False, verbose_name='是否已经同步'),
        ),
    ]
