# Generated by Django 2.2.3 on 2022-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220219_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.AddField(
            model_name='chainsafe',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
