# Generated by Django 2.2.7 on 2021-09-27 13:51

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceye_auth', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='提问内容')),
                ('answers', models.PositiveIntegerField(default=0, verbose_name='答案个数')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('status', models.CharField(choices=[('UnAnswer', 'UnAnswer'), ('Answered', 'Answered'), ('Unknown', 'Unknown')], db_index=True, default='UnAnswer', max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_cat', to='common.Category', verbose_name='问题分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceye_auth.User', verbose_name='提问人')),
            ],
            options={
                'verbose_name': '问题表',
                'verbose_name_plural': '问题表',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='回答内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('last_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relate_last_answer', to='question.Answers', verbose_name='相关回复')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_answers', to='question.Questions', verbose_name='问题')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='ceye_auth.User', verbose_name='回答者')),
            ],
            options={
                'verbose_name': '回答表',
                'verbose_name_plural': '回答表',
            },
        ),
    ]
