# Generated by Django 2.2.7 on 2021-09-30 00:59

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceye_auth', '0002_auto_20210930_0859'),
        ('common', '0002_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('chain_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='链名称')),
                ('from_addr', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='转出地址')),
                ('to_addr', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='转入地址')),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='转账金额')),
                ('tx_fee', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='转账手续费')),
                ('tx_hash', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='交易Hash')),
                ('comment', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='备注')),
                ('w_or_d', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Transfer', 'Transfer')], default='Withdraw', max_length=100, verbose_name='充值提现')),
                ('status', models.CharField(choices=[('Checking', 'Checking'), ('Checked', 'Checked'), ('Trading', 'Trading'), ('SendOut', 'SendOut'), ('Success', 'Success'), ('Fail', 'Fail'), ('CheckPass', 'CheckPass'), ('CheckRefuse', 'CheckRefuse')], default='Checked', max_length=100, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_record_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_record_user', to='ceye_auth.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包充值提现记录表',
                'verbose_name_plural': '钱包充值提现记录表',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('chain_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='链名称')),
                ('address', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='地址')),
                ('balance', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包余额')),
                ('in_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包入账')),
                ('out_amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包出账')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_rel', to='ceye_auth.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包表',
                'verbose_name_plural': '用户钱包表',
            },
        ),
        migrations.CreateModel(
            name='TansRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='金额')),
                ('trans_way', models.CharField(choices=[('Input', 'Input'), ('Output', 'Output')], default='Input', max_length=100, verbose_name='收入支出')),
                ('source', models.CharField(blank=True, default='', max_length=1280, null=True, verbose_name='支付收入来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_relate_record_asset', to='common.Asset', verbose_name='资产')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_relate_record_user', to='ceye_auth.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包交易记录表',
                'verbose_name_plural': '钱包交易记录表',
            },
        ),
    ]
