# Generated by Django 2.2.3 on 2022-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrecord',
            name='w_or_d',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Like', 'Like')], default='Withdraw', max_length=100, verbose_name='充值提现'),
        ),
    ]
