# Generated by Django 2.2.7 on 2021-09-27 13:51

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceye_auth', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=70, verbose_name='活动标题')),
                ('position', models.TextField(blank=True, max_length=200, verbose_name='活动地点')),
                ('act_time', models.TextField(blank=True, max_length=200, verbose_name='活动时间')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name='活动摘要')),
                ('company', models.TextField(blank=True, max_length=200, verbose_name='主办单位')),
                ('author', models.CharField(max_length=70, verbose_name='活动发起人')),
                ('actfee', models.CharField(max_length=70, verbose_name='活动费用')),
                ('person', models.CharField(max_length=70, verbose_name='人数上限')),
                ('is_help', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=70, verbose_name='活动是否需要赞助')),
                ('img', models.ImageField(blank=True, null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='活动图片')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('status', models.CharField(choices=[('UnStart', 'UnStart'), ('Starting', 'Starting'), ('Finished', 'Finished')], default='Starting', max_length=70, verbose_name='活动状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是开启活动')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='活动地区')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '活动地区',
                'verbose_name_plural': '活动地区',
            },
        ),
        migrations.CreateModel(
            name='CoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('coin', models.CharField(default='USDT', max_length=100, verbose_name='赞助的币种')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址表')),
            ],
            options={
                'verbose_name': '币种地址表',
                'verbose_name_plural': '币种地址表',
            },
        ),
        migrations.CreateModel(
            name='SponsorActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='参加活动的姓名')),
                ('coin', models.CharField(default='', max_length=100, verbose_name='赞助的币种')),
                ('amount', models.CharField(default='0', max_length=100, verbose_name='赞助金额')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='赞助人手机号码')),
                ('email', models.CharField(default='', max_length=100, verbose_name='赞助人邮箱')),
                ('company', models.CharField(default='', max_length=100, verbose_name='赞助人公司')),
                ('reason', models.TextField(default='', max_length=200, verbose_name='赞助原因')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity', verbose_name='赞助的活动')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ceye_auth.User', verbose_name='赞助的用户')),
            ],
            options={
                'verbose_name': '活动赞助表',
                'verbose_name_plural': '活动赞助表',
            },
        ),
        migrations.CreateModel(
            name='PartActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('username', models.CharField(default='', max_length=100, verbose_name='参加活动的姓名')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='参加活动人的联系电话')),
                ('weichat', models.CharField(default='', max_length=100, verbose_name='联系微信')),
                ('email', models.CharField(default='', max_length=100, verbose_name='联系邮箱')),
                ('company', models.CharField(default='', max_length=100, verbose_name='公司')),
                ('position', models.CharField(default='', max_length=100, verbose_name='职位')),
                ('content', models.TextField(default='', max_length=200, verbose_name='参加活动的目的')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity', verbose_name='参加的活动')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ceye_auth.User', verbose_name='参加活动的用户')),
            ],
            options={
                'verbose_name': '活动参加表',
                'verbose_name_plural': '活动参加表',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Area', verbose_name='活动地区'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Category', verbose_name='活动分类'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ceye_auth.User', verbose_name='发布活动的用户'),
        ),
    ]
