# Generated by Django 2.2.7 on 2021-09-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceye_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwalletrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.DeleteModel(
            name='UserWalletRecord',
        ),
    ]
