# Generated by Django 2.2.3 on 2022-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceye_auth', '0003_userbuycourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Outer', 'Outer'), ('Inner', 'Inner')], default='Admin', max_length=128, verbose_name='账户角色')),
                ('password', models.CharField(default='', max_length=128, verbose_name='密码')),
                ('valid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=128, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '后台用户表',
                'verbose_name_plural': '后台用户表',
            },
        ),
    ]
