# Generated by Django 2.2.7 on 2021-09-27 13:51

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceye_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='课程标题')),
                ('logo', models.ImageField(blank=True, default='block_logo/2021/05/06/1.jpeg', null=True, upload_to='block_logo/%Y/%m/%d/', verbose_name='课程图片')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name='课程摘要')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='CourseCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='CourseArtcle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('detail', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章详细')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_cs_arctcle', to='planet.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程文章表',
                'verbose_name_plural': '课程文章表',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_cat', to='planet.CourseCat', verbose_name='课程分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ceye_auth.User', verbose_name='作者'),
        ),
    ]
