# Generated by Django 2.2.7 on 2021-09-29 13:10

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ceye_auth', '0001_initial'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='课程价格'),
        ),
        migrations.AddField(
            model_name='course',
            name='process',
            field=models.CharField(default='0', max_length=100, verbose_name='课程完成度'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('CheckFail', 'CheckFail'), ('CheckPass', 'CheckPass')], default='Checking', max_length=100, verbose_name='课程状态'),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='课程阅读量'),
        ),
        migrations.AddField(
            model_name='courseartcle',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='文章阅读量'),
        ),
        migrations.CreateModel(
            name='CourseCommet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', mdeditor.fields.MDTextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('artcle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_course_artcle', to='planet.CourseArtcle', verbose_name='评论的文章')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_comment', to='planet.Course', verbose_name='评论的课程')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_user_comment', to='ceye_auth.User', verbose_name='回答者')),
            ],
            options={
                'verbose_name': '课程评论',
                'verbose_name_plural': '课程评论',
            },
        ),
    ]
