# Generated by Django 2.2.7 on 2021-09-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_auto_20210929_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='article_num',
            field=models.PositiveIntegerField(default=0, verbose_name='课时数量'),
        ),
        migrations.AddField(
            model_name='course',
            name='buyer_num',
            field=models.PositiveIntegerField(default=0, verbose_name='购买人数'),
        ),
    ]
