# Generated by Django 2.2.7 on 2021-09-29 21:53

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0003_auto_20210930_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='课程介绍'),
        ),
    ]
