# Generated by Django 2.2.7 on 2021-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0004_course_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseartcle',
            name='is_free',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='课程状态'),
        ),
        migrations.AddField(
            model_name='courseartcle',
            name='part',
            field=models.CharField(default='1', max_length=100, verbose_name='章节'),
        ),
    ]
