# Generated by Django 2.2.7 on 2021-09-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0005_auto_20210930_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseartcle',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name='文章阅读量'),
        ),
    ]
