# Generated by Django 2.2.7 on 2021-10-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0007_auto_20210930_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_pre_sell',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, verbose_name='是否预售'),
        ),
    ]
